### ISSUE TITLE
Software license?

### ISSUE THREAD

**Issue by helmut-g** [infinitespace-studios/ATI.TextureConverter#1]
I did not find a license text. What is the software license of this project? MIT, MS-PL, public domain, etc.?
I am asking for the C# wrapper. I am aware that the native library uses a different license.

**Comment by helmut-g** [comment]
@dellis1972 Can you comment on the license of this project? Thanks!

**Comment by dellis1972** [comment]
@Helikin sorry for the delay. I will release this all as MS-PL. I just need to update the source with a licence header and add a LICENCE.md file with the appropriate stuff.

**Comment by helmut-g** [comment]
Awesome! Thanks @dellis1972.
